CREATE TABLE  product (
ProductID int,
ProductName varchar(100) NOT NULL
 );
 
 select * from Product
 select * from ProductWithImage
 
 drop table Product
 
 
 create table PRODUCT (
   product_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100, INCREMENT BY 1) PRIMARY KEY,
   product_name VARCHAR(20) default NULL,
   cost     INT  default NULL
);

INSERT INTO PRODUCT (product_name, cost) VALUES ('nexus 5x', 25000);
INSERT INTO PRODUCT (product_name, cost) VALUES ('Iphone 6s', 50000);
INSERT INTO PRODUCT (product_name, cost) VALUES ('xperia zr', 15000);